### ISSUE TITLE
Rem init throws exception for newly created test app

### ISSUE THREAD

**Issue by aksonov** [ReactExtensionManager/rem#8]
```
ash-3.2$ npm install rem --save-dev
rem@0.6.8 node_modules/rem
├── osenv@0.0.3
├── read@0.1.0
├── open@0.0.2
├── colors@0.6.2
├── async@0.1.22
├── oauth@0.9.13
├── tough-cookie@0.9.8 (punycode@1.3.2)
├── connect@2.7.11 (fresh@0.1.0, cookie-signature@1.0.1, pause@0.0.1, qs@0.6.5, bytes@0.2.0, buffer-crc32@0.2.1, cookie@0.0.5, formidable@1.0.14, send@0.1.1, debug@2.2.0)
└── nconf@0.6.0 (ini@1.3.4, pkginfo@0.2.3, optimist@0.3.7)
bash-3.2$ rem init
/usr/local/lib/node_modules/react-extension-manager/build/index.js:7
var mainAsync = _asyncToGenerator(function* () {
                                          ^
SyntaxError: Unexpected token *
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by ide** [comment]
Rem requires a modern version of Node and V8. Can you try installing io.js and seeing if that fixes your issue? Best way to get set up with Node/io.js is https://github.com/creationix/nvm if you don't already have it.

**Comment by aksonov** [comment]
Thanks, it works. Missed that requirement about io.js
